-- =========================================================================
-- TEMEL ŞEMA — DEPODAKİ MIGRATION ZİNCİRİNİN EKSİK İLK HALKASI
--
-- -------------------------------------------------------------------------
-- NİYE VAR
-- -------------------------------------------------------------------------
-- Bu projede migration'lar bir noktada başladı ama TEMEL TABLOLAR ondan önce
-- Supabase panelinden elle açılmıştı. Sonuç ölçüldü:
--
--   vehicles  -> hiçbir migration OLUŞTURMUYOR, 25 migration REFERANS veriyor
--   listings  -> hiçbir migration OLUŞTURMUYOR, 10 migration REFERANS veriyor
--   profiles  -> hiçbir migration OLUŞTURMUYOR,  6 migration REFERANS veriyor
--
-- Yani depodaki migration'lar boş bir veritabanına uygulanamıyordu: ilk
-- `vehicles` referansında duruyordu. Bu, test/staging ortamı kurmayı, yeni
-- bir geliştiricinin ortamını ayağa kaldırmasını ve olası bir kurtarma
-- senaryosunu imkânsız kılıyordu.
--
-- ⚠ Veritabanının PITR yedeği de yok. Bu dosya, şemayı git'e alarak o
-- riskin ŞEMA tarafını kapatıyor. VERİYİ kapatmıyor — veri yedeği ayrı bir
-- iş.
--
-- -------------------------------------------------------------------------
-- NASIL ÜRETİLDİ
-- -------------------------------------------------------------------------
-- Canlı veritabanının katalogları (`pg_class`, `pg_attribute`,
-- `pg_constraint`, `pg_indexes`, `pg_policies`) OKUNARAK üretildi. Elle
-- yazılmadı, tahmin edilmedi.
--
-- ⚠ BU DOSYA CANLI VERİTABANINA UYGULANMADI ve uygulanmamalı. Orada zaten
-- her şey var; işi yalnızca BOŞ bir veritabanında zinciri başlatmak.
-- Yine de tamamen idempotent yazıldı (`if not exists`, `drop policy if
-- exists`, yinelenen kısıtta sessiz geçiş): yanlışlıkla çalıştırılsa bile
-- hiçbir tabloyu, kolonu ya da satırı değiştirmez.
--
-- -------------------------------------------------------------------------
-- KAPSAM — BİLEREK DAR
-- -------------------------------------------------------------------------
-- Yalnızca "hiçbir migration'ın oluşturmadığı" şeyler burada:
--   · 10 tablo + kısıtları + indeksleri + RLS
--   · 12 politika (panelden açılmış olanlar)
--
-- BURADA OLMAYANLAR ve sebebi:
--   · 16 tablo  -> zaten kendi migration'ları var
--   · 8 tetikleyici ve 8 tetikleyici fonksiyonu -> hepsi migration'larda;
--     buraya da konsaydı sıfırdan kurulumda "zaten var" hatası verirdi
--   · 9 politika -> migration'larda tanımlı
--   · RPC'ler    -> migration'larda
--   · vehicles_yedek_20260819 -> geçici yedek tablosu, şemanın parçası değil
-- =========================================================================

-- =========================================================================
-- 1. KATALOG TABLOLARI
-- Araç markası/serisi/modeli/donanımı. Sihirbazın kaskadı ve anasayfa
-- süzgeç ağacı bunlardan besleniyor (49 / 822 / 3.591 / 23.138 satır).
-- =========================================================================
create table if not exists public.car_brands (
  id bigint generated by default as identity,
  name character varying(100) not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.car_series (
  id bigint generated by default as identity,
  brand_id bigint,
  name character varying(100) not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.car_models (
  id bigint generated by default as identity,
  series_id bigint,
  name character varying(100) not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.car_packages (
  id bigint generated by default as identity,
  model_id bigint,
  name character varying(100) not null,
  created_at timestamp with time zone default now()
);

-- =========================================================================
-- 2. KULLANICI PROFİLİ
-- `auth.users`a bire bir bağlı. Silinme CASCADE: hesap silinince profil de.
-- =========================================================================
create table if not exists public.profiles (
  id uuid not null,
  first_name text not null,
  last_name text not null,
  phone_number text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_premium boolean default false,
  pazarlama_izni boolean default false not null,
  pazarlama_izni_at timestamp with time zone,
  avatar_yolu text
);

-- =========================================================================
-- 3. ARAÇ — ÜRÜNÜN MERKEZİ TABLOSU
-- Birincil anahtar PLAKA. `pin_code` karne paylaşım anahtarı,
-- `gorunurluk` aramada çıkıp çıkmayacağını belirliyor.
-- =========================================================================
create table if not exists public.vehicles (
  plate_number character varying(20) not null,
  km integer not null,
  brand character varying(100) not null,
  model character varying(100) not null,
  year integer not null,
  package character varying(100) not null,
  kasko_end_date date,
  inspection_end_date date not null,
  trust_score integer default 0 not null,
  created_at timestamp with time zone default now(),
  image_url text,
  traffic_insurance_end_date date,
  fuel_type text,
  transmission text,
  color text,
  tramer_status text default 'Bilmiyorum'::text not null,
  tramer_amount numeric,
  pin_code text,
  user_id uuid,
  series character varying(100),
  title text,
  city text,
  district text,
  body_type text,
  description text,
  damage_report jsonb default '{}'::jsonb,
  selected_features jsonb default '[]'::jsonb,
  engine_capacity text,
  trust_breakdown jsonb,
  storage_key uuid default gen_random_uuid() not null,
  sahipsiz_kaldi_at timestamp with time zone,
  belge_erisimi_kisitli boolean default false not null,
  has_warranty boolean,
  is_first_owner boolean,
  vehicle_condition text,
  gorunurluk text default 'listelenebilir'::text not null
);

-- =========================================================================
-- 4. VİTRİN KAYDI
-- Aracın pazaryeri vitrininde görünmesi. `status='active'` olan kayıt
-- "vitrin katmanı" demek ve karne PIN'ini dışarı açıyor.
-- =========================================================================
create table if not exists public.listings (
  id bigint generated by default as identity,
  vehicle_plate character varying(50),
  user_id uuid,
  title character varying(255) not null,
  description text not null,
  price numeric(12,2),
  city character varying(100) not null,
  district character varying(100) not null,
  tramer_amount numeric(12,2) default 0,
  status character varying(20) default 'active'::character varying,
  views_count integer default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  is_featured boolean default false,
  is_urgent boolean default false,
  is_trade_in boolean default false,
  previous_price numeric(12,2),
  neighborhood character varying(100),
  favorite_count integer default 0,
  contact_phone character varying(20)
);

-- =========================================================================
-- 5. BAKIM KAYITLARI · BİLDİRİMLER · SİHİRBAZ TASLAĞI
-- =========================================================================
-- ⚠ `bigserial`: canlıda kolon `nextval('maintenance_records_id_seq')`
-- varsayılanıyla duruyor (identity DEĞİL). `bigserial` birebir aynı yapıyı
-- kuruyor: bigint kolon + sahipli sequence + default.
create table if not exists public.maintenance_records (
  id bigserial,
  vehicle_plate character varying(20),
  shop_name character varying(100) not null,
  km_at_service integer not null,
  cost numeric(10,2) not null,
  summary text not null,
  created_at timestamp with time zone default now(),
  service_date date,
  service_type text,
  next_service_km integer,
  invoice_path text,
  yukleyen_user_id uuid
);

create table if not exists public.notifications (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  vehicle_id uuid,
  title character varying(255) not null,
  message text not null,
  type character varying(50) default 'info'::character varying not null,
  is_read boolean default false not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  hedef_yol text
);

create table if not exists public.vehicle_drafts (
  id uuid default gen_random_uuid() not null,
  user_id uuid,
  current_step integer default 1,
  form_data jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- =========================================================================
-- 6. KISITLAR
-- `add constraint if not exists` PostgreSQL'de yok; standart idempotent
-- kalıp bu: yinelenen nesne hatası sessizce yutuluyor.
-- =========================================================================
do $$
begin
  -- Katalog: birincil anahtarlar, marka adı tekil, zincir CASCADE.
  alter table public.car_brands add constraint car_brands_pkey primary key (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.car_brands add constraint car_brands_name_key unique (name);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.car_series add constraint car_series_pkey primary key (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.car_series add constraint car_series_brand_id_fkey
    foreign key (brand_id) references public.car_brands(id) on delete cascade;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.car_models add constraint car_models_pkey primary key (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.car_models add constraint car_models_series_id_fkey
    foreign key (series_id) references public.car_series(id) on delete cascade;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.car_packages add constraint car_packages_pkey primary key (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.car_packages add constraint car_packages_model_id_fkey
    foreign key (model_id) references public.car_models(id) on delete cascade;
exception when duplicate_table or duplicate_object then null; end $$;

do $$ begin
  alter table public.profiles add constraint profiles_pkey primary key (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.profiles add constraint profiles_id_fkey
    foreign key (id) references auth.users(id) on delete cascade;
exception when duplicate_table or duplicate_object then null; end $$;

do $$ begin
  alter table public.vehicles add constraint vehicles_pkey primary key (plate_number);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  -- ⚠ BİRİNCİL ANAHTARLA AYNI KOLONDA İKİNCİ BİR UNIQUE. Canlıda böyle
  -- duruyor (gereksiz ama zararsız); baseline'ın işi şemayı OLDUĞU GİBİ
  -- yeniden kurmak, iyileştirmek değil. Temizlenecekse ayrı bir migration.
  alter table public.vehicles add constraint vehicles_plate_number_unique_key unique (plate_number);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.vehicles add constraint vehicles_pin_code_key unique (pin_code);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.vehicles add constraint vehicles_user_id_fkey
    foreign key (user_id) references auth.users(id) on delete set null;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  -- ⚠ DÖRT DEĞER. 'Ağır Hasarlı' bugün hiçbir kayıtta yok ama kısıt onu
  -- kabul ediyor; canlıdaki hâli bu.
  alter table public.vehicles add constraint vehicles_tramer_status_gecerli
    check (tramer_status = any (array['Bilmiyorum'::text, 'Tramer Yok'::text, 'Tramer Var'::text, 'Ağır Hasarlı'::text]));
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.vehicles add constraint vehicles_vehicle_condition_check
    check ((vehicle_condition is null) or (vehicle_condition = any (array['ikinci_el'::text, 'sifir'::text])));
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.vehicles add constraint vehicles_gorunurluk_gecerli
    check (gorunurluk = any (array['gizli'::text, 'listelenebilir'::text]));
exception when duplicate_table or duplicate_object then null; end $$;

do $$ begin
  alter table public.listings add constraint listings_pkey primary key (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  -- Araç başına tek vitrin kaydı.
  alter table public.listings add constraint unique_active_listing_per_plate unique (vehicle_plate);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.listings add constraint listings_vehicle_plate_fkey
    foreign key (vehicle_plate) references public.vehicles(plate_number) on delete cascade;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.listings add constraint listings_user_id_fkey
    foreign key (user_id) references auth.users(id) on delete cascade;
exception when duplicate_table or duplicate_object then null; end $$;

do $$ begin
  alter table public.maintenance_records add constraint maintenance_records_pkey primary key (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.maintenance_records add constraint maintenance_records_vehicle_plate_fkey
    foreign key (vehicle_plate) references public.vehicles(plate_number) on delete cascade;
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  -- ⚠ SET NULL, CASCADE değil: bakım kaydını yükleyen hesap silinse bile
  -- kayıt duruyor. Sicil aracın geçmişi; yükleyenin hesabına bağlı değil.
  alter table public.maintenance_records add constraint maintenance_records_yukleyen_user_id_fkey
    foreign key (yukleyen_user_id) references auth.users(id) on delete set null;
exception when duplicate_table or duplicate_object then null; end $$;

do $$ begin
  alter table public.notifications add constraint notifications_pkey primary key (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.notifications add constraint notifications_user_id_fkey
    foreign key (user_id) references auth.users(id) on delete cascade;
exception when duplicate_table or duplicate_object then null; end $$;

do $$ begin
  alter table public.vehicle_drafts add constraint vehicle_drafts_pkey primary key (id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  -- Kullanıcı başına tek taslak.
  alter table public.vehicle_drafts add constraint vehicle_drafts_user_id_key unique (user_id);
exception when duplicate_table or duplicate_object then null; end $$;
do $$ begin
  alter table public.vehicle_drafts add constraint vehicle_drafts_user_id_fkey
    foreign key (user_id) references auth.users(id) on delete cascade;
exception when duplicate_table or duplicate_object then null; end $$;

-- =========================================================================
-- 7. İNDEKSLER
-- =========================================================================
create index if not exists idx_car_series_brand_id on public.car_series using btree (brand_id);
create index if not exists idx_car_models_series_id on public.car_models using btree (series_id);
create index if not exists idx_car_packages_model_id on public.car_packages using btree (model_id);

create index if not exists idx_listings_user_id on public.listings using btree (user_id);
create index if not exists idx_listings_status on public.listings using btree (status);
create index if not exists idx_listings_is_featured on public.listings using btree (is_featured);
create index if not exists idx_listings_location on public.listings using btree (city, district);
create index if not exists idx_listings_price on public.listings using btree (price);

-- PIN aramaları büyük/küçük harf duyarsız; tekillik de öyle olmalı.
create unique index if not exists vehicles_pin_upper_idx on public.vehicles using btree (upper(pin_code));
create unique index if not exists vehicles_storage_key_idx on public.vehicles using btree (storage_key);
create index if not exists vehicles_kasko_bitis_idx on public.vehicles using btree (kasko_end_date);
create index if not exists vehicles_muayene_bitis_idx on public.vehicles using btree (inspection_end_date);
create index if not exists vehicles_trafik_bitis_idx on public.vehicles using btree (traffic_insurance_end_date);
create index if not exists vehicles_sahipsiz_idx on public.vehicles using btree (sahipsiz_kaldi_at) where (sahipsiz_kaldi_at is not null);
create index if not exists vehicles_gorunurluk_idx on public.vehicles using btree (gorunurluk) where (gorunurluk = 'listelenebilir'::text);

create index if not exists bakim_servis_tarihi_idx on public.maintenance_records using btree (service_date);
create index if not exists bakim_fatura_yolu_idx on public.maintenance_records using btree (vehicle_plate) where (invoice_path is not null);

create index if not exists notifications_user_id_idx on public.notifications using btree (user_id);
create index if not exists notifications_is_read_idx on public.notifications using btree (is_read);

-- =========================================================================
-- 8. SATIR DÜZEYİ GÜVENLİK
-- ⚠ ONUNU DA AÇMAK ŞART. RLS kapalı bir tablo, `anon` anahtarıyla tamamen
-- okunabilir demek — bu üründe plaka, PIN ve bakım geçmişi orada duruyor.
-- =========================================================================
alter table public.car_brands          enable row level security;
alter table public.car_series          enable row level security;
alter table public.car_models          enable row level security;
alter table public.car_packages        enable row level security;
alter table public.profiles            enable row level security;
alter table public.vehicles            enable row level security;
alter table public.listings            enable row level security;
alter table public.maintenance_records enable row level security;
alter table public.notifications       enable row level security;
alter table public.vehicle_drafts      enable row level security;

-- =========================================================================
-- 9. POLİTİKALAR — YALNIZCA MIGRATION'LARDA OLMAYANLAR
-- Diğer 9 politika kendi migration'larında; buraya konsalardı sıfırdan
-- kurulumda "zaten var" hatası verirlerdi.
-- =========================================================================

-- Katalog herkese açık: anasayfadaki marka ağacı oturum açmamış ziyaretçiye
-- de çiziliyor. İçinde kişisel veri yok, yalnızca araç taksonomisi.
drop policy if exists "Katalog Herkese Açık Okunabilir" on public.car_brands;
create policy "Katalog Herkese Açık Okunabilir" on public.car_brands for select using (true);
drop policy if exists "Katalog Herkese Açık Okunabilir" on public.car_series;
create policy "Katalog Herkese Açık Okunabilir" on public.car_series for select using (true);
drop policy if exists "Katalog Herkese Açık Okunabilir" on public.car_models;
create policy "Katalog Herkese Açık Okunabilir" on public.car_models for select using (true);
drop policy if exists "Katalog Herkese Açık Okunabilir" on public.car_packages;
create policy "Katalog Herkese Açık Okunabilir" on public.car_packages for select using (true);

-- ⚠ ARAÇ VE VİTRİN KAYDI DIŞARIYA KAPALI. Anasayfa aramasının bunları
-- görebilmesi RLS'in gevşetilmesiyle DEĞİL, `arac_arama()` gibi
-- `security definer` fonksiyonların güvenli izdüşüm döndürmesiyle
-- sağlanıyor. Doğrudan tablo erişimi yalnızca sahibine.
drop policy if exists "Kullanıcılar kendi ilanlarını yönetebilir" on public.listings;
create policy "Kullanıcılar kendi ilanlarını yönetebilir" on public.listings
  for all using (auth.uid() = user_id);

drop policy if exists "Kullanıcılar sadece kendi garajına araç ekleyebilir" on public.vehicles;
create policy "Kullanıcılar sadece kendi garajına araç ekleyebilir" on public.vehicles
  for insert with check (auth.uid() = user_id);

drop policy if exists "Kullanıcılar kendi profillerini görebilir." on public.profiles;
create policy "Kullanıcılar kendi profillerini görebilir." on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "Kullanıcı kendi taslağını görebilir ve yönetebilir" on public.vehicle_drafts;
create policy "Kullanıcı kendi taslağını görebilir ve yönetebilir" on public.vehicle_drafts
  for all using (auth.uid() = user_id);

drop policy if exists "Kullanıcılar sadece kendi bildirimlerini görüntüleyebilir." on public.notifications;
create policy "Kullanıcılar sadece kendi bildirimlerini görüntüleyebilir." on public.notifications
  for select using (auth.uid() = user_id);
drop policy if exists "Kullanıcılar kendi bildirimlerini oluşturabilir" on public.notifications;
create policy "Kullanıcılar kendi bildirimlerini oluşturabilir" on public.notifications
  for insert with check (auth.uid() = user_id);
drop policy if exists "Kullanıcılar sadece kendi bildirimlerini güncelleyebilir." on public.notifications;
create policy "Kullanıcılar sadece kendi bildirimlerini güncelleyebilir." on public.notifications
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Kullanıcılar sadece kendi bildirimlerini silebilir." on public.notifications;
create policy "Kullanıcılar sadece kendi bildirimlerini silebilir." on public.notifications
  for delete using (auth.uid() = user_id);

comment on table public.vehicles is
  'Ürünün merkezi tablosu. Birincil anahtar plaka; pin_code karne paylaşım anahtarı; gorunurluk aramada çıkıp çıkmayacağını belirler.';
