-- =========================================================================
-- FAVORİLER
--
-- -------------------------------------------------------------------------
-- NİYE ŞİMDİ — EKRANDA SAHTE VERİ VARDI
-- -------------------------------------------------------------------------
-- `listings.favorite_count` sütunu şemada duruyordu ve "Vitrindeki
-- Araçlarım" ekranı onu "N Favori" diye basıyordu. Ama favori diye bir
-- tablo, bir servis ya da bir düğme YOKTU: sayaç hiçbir zaman artmıyordu.
-- Yani ekran, hiç kimsenin ölçmediği bir sayıyı ölçülmüş gibi gösteriyordu.
-- Bu, projede daha önce kaldırılan sahte veri kalıbının aynısı.
--
-- Sayacı gerçek yapmanın iki yolu vardı: (a) sütunu ve göstergeyi kaldırmak,
-- (b) altını doldurmak. Kullanıcı favori özelliğini istediği için (b).
--
-- -------------------------------------------------------------------------
-- SAYAÇ NİYE TETİKLEYİCİYLE — İSTEMCİDEN DEĞİL
-- -------------------------------------------------------------------------
-- `favorite_count` istemciden yazılabilseydi herkes kendi aracının favori
-- sayısını şişirebilirdi. Sayı, `favoriler` tablosundaki satırlardan
-- TÜRETİLİYOR; istemci o sütuna hiç dokunmuyor.
--
-- Sayaç ayrı bir sütunda tutuluyor (her okumada `count(*)` yerine): vitrin
-- listesi her açılışta tüm ilanları çekiyor ve her biri için alt sorgu
-- çalıştırmak yüz binlerce kullanıcı hedefiyle uyuşmuyor.
--
-- -------------------------------------------------------------------------
-- KENDİ ARACINI FAVORİLEYEMEZ
-- -------------------------------------------------------------------------
-- Kendi ilanını favorileyip sayacı şişirmek en bariz kötüye kullanım.
-- Politikayla değil TETİKLEYİCİYLE engelleniyor: `listings` üzerinde birden
-- çok permissive politika var ve Postgres onları OR'luyor — politikaya
-- koşul eklemek bu projede daha önce de işe yaramamıştı.
-- =========================================================================

create table if not exists public.favoriler (
  id          bigint generated by default as identity primary key,
  user_id     uuid   not null references auth.users(id) on delete cascade,
  listing_id  bigint not null references public.listings(id) on delete cascade,
  olustu      timestamptz not null default now(),

  -- Aynı ilanı iki kez favorileyememe. Arayüz zaten aç/kapa yapıyor ama
  -- kısıt veritabanında olmalı: iki sekmeden aynı anda tıklamak yeter.
  constraint favori_tek_kayit unique (user_id, listing_id)
);

comment on table public.favoriler is
  'Kullanıcının favorilediği vitrin kayıtları. listings.favorite_count bu tablodan tetikleyiciyle türetiliyor; istemci sayaca yazamıyor.';

create index if not exists favori_kullanici_idx on public.favoriler (user_id, olustu desc);
create index if not exists favori_ilan_idx      on public.favoriler (listing_id);

alter table public.favoriler enable row level security;

-- Kullanıcı YALNIZCA kendi favorilerini görüyor, ekliyor ve siliyor.
-- Başkasının neyi favorilediği görünmüyor: bu bir gizlilik sınırı.
drop policy if exists favori_oku_kendi on public.favoriler;
create policy favori_oku_kendi on public.favoriler
  for select to authenticated using (auth.uid() = user_id);

drop policy if exists favori_ekle_kendi on public.favoriler;
create policy favori_ekle_kendi on public.favoriler
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists favori_sil_kendi on public.favoriler;
create policy favori_sil_kendi on public.favoriler
  for delete to authenticated using (auth.uid() = user_id);

-- Güncelleme politikası BİLEREK yok: favori ya var ya yok, düzenlenecek
-- bir alanı bulunmuyor.

revoke all on public.favoriler from public;
revoke all on public.favoriler from anon, authenticated;
grant select, insert, delete on public.favoriler to authenticated;
grant all on public.favoriler to service_role;
grant usage, select on sequence public.favoriler_id_seq to authenticated;


-- -------------------------------------------------------------------------
-- KENDİ ARACINI FAVORİLEME ENGELİ
-- -------------------------------------------------------------------------
create or replace function public.favori_kendi_aracini_engelle()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_sahip uuid;
begin
  select user_id into v_sahip from listings where id = new.listing_id;

  if v_sahip is not null and v_sahip = new.user_id then
    raise exception 'KENDI_ARACIN';
  end if;

  return new;
end;
$$;

drop trigger if exists favori_kendi_aracini_engelle on public.favoriler;
create trigger favori_kendi_aracini_engelle
  before insert on public.favoriler
  for each row execute function public.favori_kendi_aracini_engelle();

revoke all on function public.favori_kendi_aracini_engelle() from public;
revoke all on function public.favori_kendi_aracini_engelle() from anon, authenticated;


-- -------------------------------------------------------------------------
-- SAYAÇ BAKIMI
-- -------------------------------------------------------------------------
create or replace function public.favori_sayaci_guncelle()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'INSERT' then
    update listings
       set favorite_count = coalesce(favorite_count, 0) + 1
     where id = new.listing_id;
    return new;
  end if;

  -- DELETE. `greatest(...,0)`: sayaç elle bozulmuşsa eksiye düşmesin.
  update listings
     set favorite_count = greatest(coalesce(favorite_count, 0) - 1, 0)
   where id = old.listing_id;
  return old;
end;
$$;

drop trigger if exists favori_sayaci_guncelle on public.favoriler;
create trigger favori_sayaci_guncelle
  after insert or delete on public.favoriler
  for each row execute function public.favori_sayaci_guncelle();

revoke all on function public.favori_sayaci_guncelle() from public;
revoke all on function public.favori_sayaci_guncelle() from anon, authenticated;


-- -------------------------------------------------------------------------
-- MEVCUT SAYAÇLARI GERÇEĞE EŞİTLE
--
-- Bugüne kadar sütun hiç yazılmadı ama sıfırdan farklı bir değer kalmış
-- olabilir. Tabloyla tutarlı hâle getiriliyor ki gösterilen ilk sayı da
-- doğru olsun.
-- -------------------------------------------------------------------------
update public.listings l
   set favorite_count = (select count(*) from public.favoriler f where f.listing_id = l.id);
