-- =========================================================================
-- YETKİ KİLİTLERİ — paywall artık atlanamıyor
--
-- Demo ödeme ekranı kuruldu ama ayrıcalıklar hâlâ istemciden yazılabiliyordu.
-- Ölçülen açıklar:
--
--   listings.is_featured  kullanıcının kendi satırında serbest  -> vitrin bedava
--   ilan/araç kotası      hiç uygulanmıyor, yalnızca ekrana basılıyor
--   profiles INSERT       with_check: true (koşul YOK)          -> bedava premium
--   profiles UPDATE       politika HİÇ YOK                      -> profil düzenlenemiyor
--
-- -------------------------------------------------------------------------
-- NEDEN POLİTİKA DEĞİL TETİKLEYİCİ
-- -------------------------------------------------------------------------
-- `vehicles` üzerinde INSERT'e izin veren İKİ permissive politika var:
-- "Kullanıcılar sadece kendi aracını yönetebilir" (ALL) ve "...kendi garajına
-- araç ekleyebilir" (INSERT). Postgres aynı komut için birden fazla permissive
-- politikayı OR'luyor — yani birine kota koşulu eklemek hiçbir şeye yaramaz,
-- diğeri satırı zaten geçirir. Bu tuzağa bu projede daha önce iki kez
-- düşüldü.
--
-- Tetikleyici hangi politikanın geçirdiğine bakmaz; satır yazılmadan önce
-- çalışır ve OR'lanamaz. Kilit için doğru araç bu.
--
-- -------------------------------------------------------------------------
-- AYRICALIK ARTIK BOOLEAN'DAN DEĞİL SATIN ALMA KAYDINDAN TÜRÜYOR
-- -------------------------------------------------------------------------
-- `satin_almalar` tablosu tek gerçek. RevenueCat/iyzico webhook'u geldiğinde
-- aynı tabloya yazacak — şema değişmeyecek, yalnızca `saglayici` alanı
-- 'demo' yerine sağlayıcının adını taşıyacak.
--
-- Kullanıcı bu tabloya YAZAMIYOR. Demo satın alma `demo_satin_alma()`
-- fonksiyonundan geçiyor; adı bilerek "demo" — gerçek tahsilat bağlandığında
-- yetkisi geri alınacak tek yer orası.
--
-- -------------------------------------------------------------------------
-- KOTA YALNIZCA YENİ KAYITTA — mevcut araçlar korunuyor
-- -------------------------------------------------------------------------
-- Tetikleyici INSERT'e bakıyor, var olan satırlara değil. Bugün 10 aracı olan
-- bir kullanıcının garajı kilitlenmiyor; yalnızca 11. araç ücrete tabi.
--
-- DEVİR KOTAYA TABİ DEĞİL, bilerek: devir `vehicles.user_id`'yi GÜNCELLİYOR,
-- yeni satır eklemiyor. Ayrıca devrin kendi ücreti (₺199) ek araç kaydından
-- (₺149) yüksek — aracı satın alan kişiden ikinci kez ücret almak yanlış olur.
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1 · SATIN ALMA KAYITLARI
-- -------------------------------------------------------------------------
create table if not exists public.satin_almalar (
  id                    bigint generated by default as identity primary key,
  user_id               uuid not null references auth.users(id) on delete cascade,

  -- src/data/paketler.js içindeki `kod` alanıyla aynı: 'devir',
  -- 'sicil_geri_yukleme', 'ek_arac', 'vitrin'
  urun_kodu             text not null,

  saglayici             text not null default 'demo',
  saglayici_referansi   text,

  tutar                 numeric(10,2),
  para_birimi           text not null default 'TRY',

  durum                 text not null default 'bekliyor'
                          check (durum in ('bekliyor','tamamlandi','iade')),

  -- Hangi araç için kullanıldı. null = henüz harcanmadı. Tüketilebilir
  -- ürünlerin bir kez kullanılmasını bu alan sağlıyor.
  hedef_plaka           text,

  olustu                timestamptz not null default now(),
  tamamlandi_at         timestamptz
);

comment on table public.satin_almalar is
  'Ücretli işlemlerin kaydı. Ayrıcalıklar bu tablodan türetilir; istemcinin yazdığı boolean alanlardan DEĞİL. Ödeme sağlayıcısı bağlandığında webhook aynı tabloya yazacak.';

create index if not exists satin_alma_kullanici_idx
  on public.satin_almalar (user_id, urun_kodu, durum);

-- Harcanmamış kayıtları hızlı bulmak için.
create index if not exists satin_alma_harcanmamis_idx
  on public.satin_almalar (user_id, urun_kodu)
  where durum = 'tamamlandi' and hedef_plaka is null;

alter table public.satin_almalar enable row level security;

-- Kullanıcı kendi kayıtlarını OKUR. Yazma yok: ayrıcalık istemciden
-- yazılabilseydi tüm kilit anlamsız olurdu.
drop policy if exists satin_alma_oku_kendi on public.satin_almalar;
create policy satin_alma_oku_kendi on public.satin_almalar
  for select to authenticated
  using (auth.uid() = user_id);


-- -------------------------------------------------------------------------
-- 2 · ARAÇ KOTASI
--
-- İlk araç ücretsiz. 2. ve sonrası için ya premium üyelik ya da harcanmamış
-- bir "ek_arac" satın alması gerekiyor. Satın alma bu işlemde TÜKETİLİYOR.
-- -------------------------------------------------------------------------
create or replace function public.vehicles_kota_denetle()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  v_uid       uuid := auth.uid();
  v_mevcut    integer;
  v_premium   boolean;
  v_satin_id  bigint;
begin
  -- Sunucu tarafı (service_role / postgres) kotaya tabi değil: devir,
  -- geri yükleme ve yönetim işlemleri buradan geçiyor.
  if v_uid is null then
    return new;
  end if;

  select count(*) into v_mevcut
  from public.vehicles where user_id = v_uid;

  -- İlk araç her zaman ücretsiz.
  if v_mevcut < 1 then
    return new;
  end if;

  select coalesce(is_premium, false) into v_premium
  from public.profiles where id = v_uid;

  if coalesce(v_premium, false) then
    return new;
  end if;

  -- Harcanmamış ek araç hakkı var mı? Varsa TÜKETİLİYOR.
  select id into v_satin_id
  from public.satin_almalar
  where user_id = v_uid and urun_kodu = 'ek_arac'
    and durum = 'tamamlandi' and hedef_plaka is null
  order by olustu
  limit 1
  for update skip locked;

  if v_satin_id is not null then
    update public.satin_almalar
    set hedef_plaka = new.plate_number
    where id = v_satin_id;
    return new;
  end if;

  -- Mesaj kullanıcıya gösterilecek: ne olduğunu ve ne yapacağını söylüyor.
  raise exception 'EK_ARAC_GEREKLI'
    using hint = 'İlk aracınız ücretsiz. Yeni araç eklemek için Ek Araç Kaydı gerekiyor.';
end;
$$;

drop trigger if exists vehicles_kota_denetle on public.vehicles;
create trigger vehicles_kota_denetle
  before insert on public.vehicles
  for each row execute function public.vehicles_kota_denetle();


-- -------------------------------------------------------------------------
-- 3 · VİTRİN KİLİDİ
--
-- `is_featured` artık istemciden yazılamıyor; harcanmamış bir "vitrin"
-- satın alması gerekiyor ve o satın alma bu ilana bağlanıyor.
-- -------------------------------------------------------------------------
create or replace function public.listings_vitrin_denetle()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  v_uid      uuid := auth.uid();
  v_satin_id bigint;
  v_onceki   boolean;
begin
  if v_uid is null then
    return new;
  end if;

  v_onceki := case when tg_op = 'UPDATE' then coalesce(old.is_featured, false) else false end;

  -- Vitrinden çıkmak ya da vitrin dışı bir güncelleme serbest.
  if not coalesce(new.is_featured, false) or v_onceki then
    return new;
  end if;

  -- Bu plaka için zaten kullanılmış bir vitrin hakkı varsa tekrar istemiyoruz
  -- (ilan güncellemelerinde her seferinde ücret alınmamalı).
  if exists (
    select 1 from public.satin_almalar
    where user_id = v_uid and urun_kodu = 'vitrin'
      and durum = 'tamamlandi' and hedef_plaka = new.vehicle_plate
  ) then
    return new;
  end if;

  select id into v_satin_id
  from public.satin_almalar
  where user_id = v_uid and urun_kodu = 'vitrin'
    and durum = 'tamamlandi' and hedef_plaka is null
  order by olustu
  limit 1
  for update skip locked;

  if v_satin_id is null then
    raise exception 'VITRIN_GEREKLI'
      using hint = 'Vitrin dopingi satın alınmadan ilan öne çıkarılamaz.';
  end if;

  update public.satin_almalar
  set hedef_plaka = new.vehicle_plate
  where id = v_satin_id;

  return new;
end;
$$;

drop trigger if exists listings_vitrin_denetle on public.listings;
create trigger listings_vitrin_denetle
  before insert or update on public.listings
  for each row execute function public.listings_vitrin_denetle();


-- -------------------------------------------------------------------------
-- 4 · PREMIUM BAYRAĞI KİLİDİ
--
-- `is_premium` yalnızca sunucu tarafından yazılabiliyor. Kullanıcı kendi
-- satırını oluştururken ya da güncellerken bu alana dokunamıyor.
-- -------------------------------------------------------------------------
create or replace function public.profiles_premium_koru()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if auth.uid() is null then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.is_premium := false;
  else
    -- Sessizce eski değere döndürülüyor, hata verilmiyor: kullanıcı bu alanı
    -- kasıtlı göndermiş olmayabilir (istemci tüm satırı geri yazıyor olabilir)
    -- ve profil güncellemesini bu yüzden kırmak yanlış olur.
    new.is_premium := old.is_premium;
  end if;

  return new;
end;
$$;

drop trigger if exists profiles_premium_koru on public.profiles;
create trigger profiles_premium_koru
  before insert or update on public.profiles
  for each row execute function public.profiles_premium_koru();


-- -------------------------------------------------------------------------
-- 5 · PROFİL POLİTİKALARI
--
-- INSERT koşulsuzdu (`with_check: true`): kayıt olan biri BAŞKASININ profilini
-- oluşturabiliyordu. Artık yalnızca kendi satırı.
--
-- E-posta doğrulaması kapalı olduğu doğrulandı (kullanıcılar ~30 ms içinde
-- onaylanıyor), yani `signUp` anında oturum açılıyor ve kayıt akışındaki
-- istemci INSERT'i `auth.uid() = id` koşulunu geçiyor. Doğrulama açılırsa bu
-- akış profil oluşturmayı `auth.users` tetikleyicisine taşımayı gerektirir.
-- -------------------------------------------------------------------------
drop policy if exists "Kayıt anında profil oluşturulmasına izin ver" on public.profiles;
create policy "profil_olustur_kendi" on public.profiles
  for insert to authenticated
  with check (auth.uid() = id);

-- UPDATE politikası HİÇ YOKTU: kullanıcı adını bile değiştiremiyordu.
-- Hesabım ekranının ön koşulu bu.
drop policy if exists "profil_guncelle_kendi" on public.profiles;
create policy "profil_guncelle_kendi" on public.profiles
  for update to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);


-- -------------------------------------------------------------------------
-- 6 · DEMO SATIN ALMA
--
-- ⚠ GERÇEK TAHSİLAT BAĞLANDIĞINDA YETKİSİ GERİ ALINACAK TEK YER BURASI.
-- Adı bilerek "demo": kod tabanında arandığında bulunması ve unutulmaması
-- için. Sağlayıcı webhook'u aynı tabloya yazacağı için şema değişmeyecek.
-- -------------------------------------------------------------------------
create or replace function public.demo_satin_alma(p_urun_kodu text, p_tutar numeric default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_id  bigint;
begin
  if v_uid is null then
    return jsonb_build_object('hata','oturum_yok');
  end if;

  if p_urun_kodu not in ('devir','sicil_geri_yukleme','ek_arac','vitrin') then
    return jsonb_build_object('hata','bilinmeyen_urun');
  end if;

  insert into public.satin_almalar
    (user_id, urun_kodu, saglayici, tutar, durum, tamamlandi_at)
  values
    (v_uid, p_urun_kodu, 'demo', p_tutar, 'tamamlandi', now())
  returning id into v_id;

  return jsonb_build_object('basarili', true, 'satin_alma_id', v_id, 'urun', p_urun_kodu);
end;
$$;


-- -------------------------------------------------------------------------
-- 7 · YETKİLER
--
-- İki revoke da yazılıyor: `from public` adıyla verilmiş grant'i bırakır,
-- `from anon, authenticated` PUBLIC kalıtımını bırakır. Üçü de gerekli.
-- -------------------------------------------------------------------------
revoke all on function public.vehicles_kota_denetle()   from public;
revoke all on function public.vehicles_kota_denetle()   from anon, authenticated;

revoke all on function public.listings_vitrin_denetle() from public;
revoke all on function public.listings_vitrin_denetle() from anon, authenticated;

revoke all on function public.profiles_premium_koru()   from public;
revoke all on function public.profiles_premium_koru()   from anon, authenticated;

revoke all on function public.demo_satin_alma(text, numeric)    from public;
revoke all on function public.demo_satin_alma(text, numeric)    from anon;
grant execute on function public.demo_satin_alma(text, numeric) to authenticated;
